# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # -------------------------------------------------------------
    # `````````````````````````````````````````````````````````````
    # Editable Area - Define Your Required Specs in this section
    # before running vagrant up.
    # `````````````````````````````````````````````````````````````

	# Memory of VM in MB
	vm_memory = 2600

	# Virtual CPU's on VM
	vm_cpu_count = 2

	# END OF EDITABLE AREA
	# _____________________________________________________________
    # `````````````````````````````````````````````````````````````

    config.ssh.forward_agent = true
    config.ssh.insert_key = true

    config.vm.define "api.deliverycalculator.local" do |node|

        node.vm.provider "virtualbox" do |vb|
            vb.name = "DeliveryCalculator VM"
            vb.gui = false
            vb.memory = vm_memory
            vb.cpus = vm_cpu_count
            vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
        end

        node.vm.box = "ubuntu/bionic64"

        node.vm.network "private_network", ip: "192.168.37.10"
        node.vm.host_name = "api.deliverycalculator.local"
        node.hostsupdater.aliases = [
            "api.deliverycalculator.local",
        ]

        node.vm.synced_folder ".", "/vagrant", type: "nfs"
        
        node.disksize.size = '30GB'

        config.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "/vagrant/scripts/ansible/dev.yml"
            ansible.extra_vars = {
                private_interface: "192.168.37.10",
                hostname: "api.deliverycalculator.local",
                fqdn: "api.deliverycalculator.local",
                ansible_connection: "local",
            }
        end
    end
end
